let funnyJokes = [
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "I'm on a whiskey diet. I've lost three days already.",
    "Why do chicken coops only have two doors? Because if they had four, they'd be a chicken sedan.",
    "Why don’t scientists trust atoms? Because they make up everything.",
    "I have a photographic memory, but I always forget to bring my camera.",
    "I used to be indecisive. Now I'm not sure.",
    "I have a joke about construction, but I'm still working on that.",
    "I'm reading a book about teleportation. It's bound to get me somewhere.",
    "I'm not lazy, I'm just energy efficient.",
    "Why did the cookie go to the doctor? Because he was feeling crumbly.",
    "What do you get when you cross a snowman and a shark? Frostbite!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I tried to start a hot air balloon business, but it never took off.",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "I told my wife she was overreacting. She just rolled her eyes and left without saying anything. I hate it when she does that.",
    "I used to play piano by ear. Now I use my hands.",
    "Why did the hipster burn his tongue? He drank his coffee before it was cool.",
    "I'm not arguing, I'm just explaining why I'm right.",
    "Why don't seagulls fly by the bay? Because then they'd be bagels!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I'm not clumsy. The floor just hates me, the table and chairs are bullies, and the walls get in my way.",
    "I used to be a baker, but I couldn't raise the dough.",
    "I don't always tell dad jokes, but when I do, he laughs.",
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "Why do birds fly south in the winter? Because it's too far to walk!",
    "I'm not a vegetarian because I love animals. I'm a vegetarian because I hate plants.",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why did the coffee file a police report? It got mugged!",
    "Why can't you hear a pterodactyl go to the bathroom? Because the P is silent!",
    "I'm reading a book on the history of glue. I just can't seem to put it down.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "I'm not a morning person. I'm not an afternoon person. I'm not an evening person. I'm a night owl.",
    "What do you call fake spaghetti? An impasta!",
    "Why don't ants get sick? They have tiny ant-bodies!",
    "I don't trust people who don't like dogs, but I trust dogs when they don't like people.",
    "Why was the math book sad? Because it had too many problems.",
    "What do you call a can opener that doesn’t work? A can’t opener!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why don’t scientists trust atoms? Because they make up everything.",
    "What did the grape say when it got stepped on all day? Nothing, it just let out a little wine.",
    "Why don’t oysters give to charity? Because they’re shellfish.",
    "Why did the coffee file a police report? It got mugged.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why did the hipster burn his tongue? He drank his coffee before it was cool.",
    "Why did the chicken join a band? Because it already had drumsticks.",
    "Why did the frog call his insurance company? He had a jump in his car.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Why did the orange stop rolling down the hill? It ran out of juice.",
    "Why did the banana go to the doctor? Because it wasn't peeling well.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "Why did the cookie go to the doctor? It felt crummy.",
    "Why was the broom late? It swept in.",
    "Why did the golfer wear two pairs of pants? In case he got a hole in one.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
    "Why did the bicycle fall over? It was two-tired.",
    "Why did the cookie go to the doctor? Because it was feeling crumbly.",
    "Why was the belt sent to jail? For holding up pants.",
    "Why did the chicken cross the playground? To get to the other slide.",
    "Why did the man run around his bed? To catch up on his sleep.",
    "Why don't they play poker in the jungle? Too many cheetahs.",
    "Why did the dog go to the vet? It was feeling ruff.",
    "Why did the toilet paper roll down the hill? To get away from the crack.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "Why did the math book look so sad? Because it had too many problems.",
    "Why do fish live in saltwater? Because pepper water makes them sneeze.",
    "Why did the cow go to outer space? To see the moooon!",
    "Why did the golfer wear two pairs of pants? In case he got a hole-in-one.",
    "Why did the chicken cross the road? To get to the other side.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why do hummingbirds hum? Because they don't know the words.",
    "Why do bicycles fall over? Because they're two-tired.",
    "Why do seagulls fly over the sea? Because if they flew over the bay they'd be bagels.",
    "Why did the man put his money in the freezer? He wanted cold hard cash.",
    "Why did the banana go to the doctor? Because it wasn't peeling well.",
    "Why don't skeletons fight each other? They don't have.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don’t scientists trust atoms? Because they make up everything.",
    "I’m reading a book on the history of glue. I just can’t seem to put it down.",
    "I told my wife she was overreacting. She just rolled her eyes and left me.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don’t seagulls fly by the bay? Because then they would be bagels.",
    "Why did the math book look sad? Because it had too many problems.",
    "Why don’t ants get sick? Because they have tiny ant-bodies.",
    "I’m on a whiskey diet. I’ve lost three days already.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "Why don’t scientists trust atoms? Because they make up everything.",
    "Why did the hipster burn his tongue? He drank his coffee before it was cool.",
    "Why can’t a nose be 12 inches long? Because then it would be a foot.",
    "Why was the math book sad? Because it had too many problems.",
    "Why did the cookie go to the doctor? Because it felt crummy.",
    "Why do bananas have to put on sunscreen before they go to the beach? Because they might peel!",
    "Why did the bicycle fall over? Because it was two-tired.",
    "Why did the mushroom go to the party? Because he was a fungi.",
    "What do you get when you cross a snowman and a shark? Frostbite.",
    "What do you call an alligator in a vest? An investi-gator.",
    "Why don’t scientists trust atoms? Because they make up everything.",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why did the chicken go to the séance? To talk to the other side.",
    "Why did the vampire go to art school? He wanted to learn how to draw blood.",
    "Why did the scarecrow win an award? Because he was out-standing in his field.",
    "Why did the cookie go to the doctor? Because he felt crummy.",
    "Why don’t elephants use computers? Because they’re afraid of mice.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the frog call his insurance company? He had a jump in his car.",
    "Why don’t ghosts use elevators? They lift their spirits.",
    "Why do bees hum? Because they don’t know the words.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why was the computer cold? It left its Windows open.",
    "Why did the cookie go to the doctor? It felt crummy.",
    "Why did the banana go to the doctor? It wasn’t peeling well.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you get when you cross a snowman and a dog? Frostbite.",
    "Why did the banana go to the doctor? Because it wasn’t peeling well.",
    "Why did the tomato turn red? Because it saw the salad dressing."
  ]
  
  
  let number=Math.floor(Math.random()*funnyJokes.length)
  
  let randJoke=funnyJokes[number]
  
  
  document.getElementById("jokes").innerHTML=randJoke
  
  //
  let generateJoke=()=>{
  let number=Math.floor(Math.random()*funnyJokes.length)
  let randJoke=funnyJokes[number]
  document.getElementById("jokes").innerHTML=randJoke
    
  }
  
  let j= document.getElementById("new")
  j.addEventListener("click",generateJoke)